### ISSUE TITLE
Plugin doesent respond when surtain other plugins are loaded

### ISSUE THREAD

**Issue by bafplus** [CruAlbania/hubot-better-help#2]
Bot doesent respond to "help" when surtain plugins are loaded (telegram adapter).
Seems to have something to do with markdown (no coder so cant help with any info on that)

**Comment by gburgett** [comment]
Could you give me a list of these other plugins and their NPM or git repositories?

**Comment by bafplus** [comment]
I know 2, one is a private one so cant share, the other is the stock hubot-google-images

**Comment by bafplus** [comment]
using this adapter (could be thats the issue): https://www.npmjs.com/package/hubot-telegram

**Comment by bafplus** [comment]
when i run it with shell:
[Fri Jun 30 2017 22:15:00 GMT+0200 (CEST)] ERROR Cant parse help from  res-wikia  because it doesnt use the normal index.coffee template.
 TypeError: robot.respond is not a function
  at exports.default (/home/server/hubot/node_modules/res-wikia/wikia.js:38:11)
  at HelpParser.parseHelpFromModule (/home/server/hubot/node_modules/hubot-better-help/scripts/better-help/parser.js:116:32)
  at HelpParser.parseHelpFromModules (/home/server/hubot/node_modules/hubot-better-help/scripts/better-help/parser.js:144:26)
  at Fs.readFile.err (/home/server/hubot/node_modules/hubot-better-help/scripts/better-help/parser.js:79:30)
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)

**Comment by gburgett** [comment]
Is res-wikia the private module?

The standard hubot script yeoman generator creates an index.coffee file in the root of the module that looks like this:

```coffeescript
fs = require 'fs'
path = require 'path'

module.exports = (robot, scripts) ->
  scriptsPath = path.resolve(__dirname, 'scripts')
  fs.exists scriptsPath, (exists) ->
    if exists
      for script in fs.readdirSync(scriptsPath)
        if scripts? and '*' not in scripts
          robot.loadFile(scriptsPath, script) if script in scripts
        else
          robot.loadFile(scriptsPath, script)
```
hubot-better-help calls this file with a mock robot that only has the method "loadFile".  This is how I get the file contents of all the scripts that get loaded, in order to parse the headers.  In this case the module doesn't do the normal thing, and hubot-better-help doesn't seem to be handling the error correctly.  I'll look into this more tomorrow, but the best I can do is add better error handling so that it'll still respond to `hubot help`, it just won't have any help for that specific module.

Does the private module have a help header like the other hubot modules?

**Comment by gburgett** [comment]
I just pushed version 0.1.1 which I hope fixes the issue.  Let me know if it works!

**Comment by bafplus** [comment]
Yes it does have the help header.
But making it handle errors better or even "ignoring" the help for that plugin would be a good thing.

**Comment by bafplus** [comment]
it seems to work.
However...the base "help" doesent work, but that seems to be an adapter issue.

**Comment by gburgett** [comment]
Great!  This package is intended to replace the base help.  There's no use in having both enabled since they both respond to "hubot help", and whichever is loaded first will win

**Comment by gburgett** [comment]
Fixed in v0.1.1

**Comment by bafplus** [comment]
i ment the base help command...just saying "help" doesent produce the initial help output, saying "help {plugin}" does output help for that plugin.  It seems that that is caused by some extra plugins icw the telegram adapter.  The adapter seems to not be able to handle that output (mardown???).  If i remove that extra plugin(s) it does work.

**Comment by bafplus** [comment]
You can ping me in telegram (@bafplus) if i need to show you.
